name: test

on: [ push ]

jobs:
  all:
    name: test

    strategy:
      fail-fast: true # saves ci time, won't be worth it if it even runs other platform
      matrix:
        os: [ ubuntu-20.04 ]
        go-version: [ 1.16.0 ]
        target: [ 'test' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/${{ github.repository }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: ${{ matrix.go-version }}
        id: go

      - name: make ${{ matrix.target }}
        shell: bash
        run: |
          make $target
        working-directory: ${{ github.workspace }}/${{ github.repository }}
        env:
          target: ${{ matrix.target }}